
site_structure=[
    ["Home", "index.html"],
    ["About Us", "node_about_us.html",
     [["School Map", "school-map.html"],
      ["External tour", "gallery_school_tour.nojs.html"],
      ["Staff", "staff.html"],
      ["Governors", "governors.html"],
      ["History", "history.html"],
      ["Mission","mission.html"],
      ["Uniform", "uniform.html"],
      ["Meals", "school_meals.html"], 
      ["Trips", "school_trips_general.html"],
      ["International Ties", "international.html"]]],
    ["Newsletters", "node_newsletters.html",
     [["20th May 2009", "newsletter-20090520.html"],
      ["13th May 2009", "newsletter-20090513.html"],
      ["6th May 2009", "newsletter-20090506.html"]]],
    ["Classes", "node_classes.html",
     [["Foundation", "node_class-f.html",
       [["Topic web", "topic-web-year-f.html"]]],
      ["Year 1", "node_class-1.html",
       [["Topic web", "topic-web-year-1.html"]]],
      ["Year 2", "node_class-2.html",
       [["Topic web", "topic-web-year-2.html"]]],
      ["Year 3", "node_class-3.html",
       [["Topic web", "topic-web-year-3.html"]]],
      ["Year 4", "node_class-4.html",
       [["Topic web", "topic-web-year-4.html"]]],
      ["Year 5", "node_class-5.html",
       [["Topic web", "topic-web-year-5.html"]]],
      ["Year 6", "node_class-6.html",
       [["Topic web", "topic-web-year-6.html"]]]]],
    ["Policies", "node_policies.html",
     [["Homework", "homework.html"],
      ["Behaviour", "behaviour.html"],
      ["School Times", "school_hours.html"],
      ["Anti Bullying", "bullying.html"]]],
    ["Procedures", "node_procedures.html",
     [["Admissions", "admission.html"],
      ["Medical", "medical.html"],
      ["Collection", "collection.html"],
      ["Absence", "absence.html"]]],
    ["Downloads", "downloads.html"],
    ["SWGfL Merlin", "node_merlin.html",
     [["Log in", "https://secure.merlin.swgfl.org.uk/"]]],
    ["Contact Us", "contact.html"]]
