
site_structure=[
    ["Home", "index.html"],
    ["About Us", "node_about_us.html",
     [["School Map", "school-map.html"],
      ["Staff", "staff.html"],
      ["Governors", "governors.html"],
      ["History", "history.html"],
      ["Mission","mission.html"],
      ["Uniform", "uniform.html"],
      ["International Ties", "international.html"]]],
    ["Newsletters", "node_newsletters.html",
     [["13th May 2009", "newsletter-20090513.html"],
      ["6th May 2009", "newsletter-20090506.html"]]],
    ["Policies", "node_policies.html",
     [["Homework", "homework.html"],
      ["Behaviour", "behaviour.html"],
      ["School Times", "school_hours.html"],
      ["Anti Bullying", "bullying.html"]]],
    ["Procedures", "node_procedures.html",
     [["Medical", "medical.html"],
      ["Collection", "collection.html"],
      ["Absence", "absence.html"]]],
    ["School Meals", "school_meals.html"], 
    ["Admissions", "admission.html"],
    ["Trips", "node_trips.html",
     [["General", "school_trips_general.html"]]],
    ["Galleries", "node_galleries.html",
     [["External tour", "gallery_school_tour.nojs.html"]]],
    ["Contact", "contact.html"]]
