
site_structure=[
    ["Home", "index.html"],
    ["About Us", "node_about_us.html",
     [["School Map", "school-map.html"],
      ["Staff", "staff.html"],
      ["Governors", "governors.html"],
      ["History", "history.html"],
      ["Mission","mission.html"],
      ["Uniform", "uniform.html"],
      ["School Meals", "school_meals.html"], 
      ["International Ties", "international.html"]]],
    ["Newsletters", "node_newsletters.html",
     [["13th May 2009", "newsletter-20090513.html"],
      ["6th May 2009", "newsletter-20090506.html"]]],
#     ["Policies", "node_policies.html",
#      [["Homework", "homework.html"],
#       ["Behaviour", "behaviour.html"],
#       ["School Times", "school_hours.html"],
#       ["Anti Bullying", "bullying.html"]]],
    ["Procedures", "node_procedures.html",
     [["Admissions", "admission.html"],
      ["Medical", "medical.html"],
      ["Collection", "collection.html"],
      ["Absence", "absence.html"]]],
    ["Trips", "node_trips.html",
     [["General", "school_trips_general.html"]]],
    ["Galleries", "node_galleries.html",
     [["External tour", "gallery_school_tour.nojs.html"]]],
    ["SWGfL Merlin", "node_merlin.html",
     [["Log in", "https://secure.merlin.swgfl.org.uk/"]]],
    ["Contact Us", "contact.html"]]
